name: Creating prerelease
run-name: "Creating prerelease as bumped version detected"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Push events to matching version *, i.e. 1.0, 20.15.10

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH      

      - name: Install dependencies
        run: poetry install

      #- name: GitHub Release
       # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run: >-
         # gh release create ${{ github.ref_name }}
         # --generate-notes
         # --title "Version ${{ github.ref_name }}"
         # --prerelease

      - name: Build and publish to TestPyPI
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TESTPYPI_API }}
          poetry publish --build -r testpypi
